import { logicPlusUnits } from './units-logic-plus.mjs';
import { hardwareUnits } from './units-hardware.mjs';
import { mechanismUnits } from './units-mechanisms.mjs';
import { visionUnits } from './units-vision.mjs';
import { logicDepth } from './depth-logic.mjs';
import { logicPlusDepth } from './depth-logic-plus.mjs';
import { hardwareDepth } from './depth-hardware.mjs';
import { mechanismsDepth } from './depth-mechanisms.mjs';
import { visionDepth } from './depth-vision.mjs';

const foundationUnits = [
  {id:'sequence',title:'Think like a robot',tag:'Pseudocode & sequencing',icon:'01',minutes:8,summary:'Turn an idea into clear, ordered instructions.',concept:'Pseudocode is a plan written for people. It describes what a program should do without requiring Java or Blocks syntax. A robot follows the instructions you give it in order—not the instructions you meant to give it.',connection:'Before writing an FTC autonomous routine, your team can agree on a simple step-by-step plan.',example:'WAIT FOR START\nCLOSE claw\nDRIVE forward for 1 second\nSTOP drivetrain\nOPEN claw',explain:['Wait for the start signal before moving.','Close the claw before carrying an object.','Stop the drivetrain before releasing the object.'],task:'Your robot starts holding an object with its claw open. Write a sequence that waits for start, closes the claw, drives forward for 2 seconds, stops the drivetrain, and then opens the claw.',criteria:['Wait for start before any action.','Close the claw before driving.','Drive forward for 2 seconds, then explicitly stop.','Open the claw only after stopping.'],hint:'Imagine reading each line aloud while a teammate acts it out. What happens if you open the claw before you stop?',quiz:{q:'Why does the order of instructions matter?',options:['The robot carries out actions in the given order.','Pseudocode must always use exactly five lines.','Robots can guess the intended order.'],answer:0,why:'A sequence is ordered. Changing the order changes what the robot does.'}},
  {id:'variables',title:'Give your robot a memory',tag:'Variables & arithmetic',icon:'02',minutes:10,summary:'Store values and update them as your robot works.',concept:'A variable is a named value that can change. SET count = 0 stores zero. SET count = count + 1 reads the old value, adds one, and stores the new value. Use meaningful names and include units for measurements.',connection:'Robots track things such as collected objects, target distances, and motor power. In these lessons motor power ranges from -1 to 1.',example:'SET objectsCollected = 0\nCOLLECT one object\nSET objectsCollected = objectsCollected + 1\nDISPLAY objectsCollected',explain:['Initialize the count before using it.','Collecting changes the physical world.','Updating the variable changes the program’s memory.'],task:'Start with 0 deliveries. Deliver one object, increase deliveries by 1, deliver another object, increase it again, and display the total. State the final value in a comment.',criteria:['Initialize a clearly named delivery count to 0.','Represent two delivery actions.','Increment the count after each delivery.','Display the total and correctly identify it as 2.'],hint:'Use the same variable on both sides of an update: SET deliveries = deliveries + 1.',quiz:{q:'After SET count = 2 and SET count = count + 1, what is count?',options:['2','3','1'],answer:1,why:'The old value 2 plus 1 becomes the new stored value 3.'}},
  {id:'decisions',title:'Make the right call',tag:'IF / ELSE & comparisons',icon:'03',minutes:10,summary:'Choose an action using a sensor reading.',concept:'A condition is a question with a true or false answer. IF runs one branch when the condition is true; ELSE runs the other branch. Comparisons such as <, >, and = ask how two values relate.',connection:'A distance sensor can help a robot decide whether an obstacle is too close. This example is one decision; continuous checking comes in the loops unit.',example:'SET distanceCm = READ distance sensor\nIF distanceCm < 20 THEN\n  STOP drivetrain\nELSE\n  DRIVE forward at power 0.3\nEND IF',explain:['Read the sensor into a variable with clear units.','Below 20 cm, the true branch stops the robot.','At exactly 20 cm, < 20 is false, so the ELSE branch runs.'],task:'Read a distance sensor in centimeters. If the distance is 15 cm or less, stop the drivetrain. Otherwise drive forward at power 0.2. Explain what happens at exactly 15 cm in a comment.',criteria:['Read a distance sensor in centimeters.','Use a condition that includes 15 (<= 15 or equivalent).','Stop when the distance is 15 or less.','Drive at 0.2 otherwise and explain the boundary case.'],hint:'“Less than” and “less than or equal to” behave differently at the boundary.',quiz:{q:'Which comparison includes exactly 15 cm?',options:['distance < 15','distance > 15','distance <= 15'],answer:2,why:'The equals part includes the boundary value of 15.'}},
  {id:'boolean',title:'Combine your conditions',tag:'AND, OR & NOT',icon:'04',minutes:10,summary:'Build decisions from more than one piece of information.',concept:'AND is true only when both conditions are true. OR is true when at least one is true. NOT reverses true and false. Parentheses make grouped conditions easier to read.',connection:'An intake should run only when the driver requests it and the robot has room for an object.',example:'IF intakeButtonPressed AND NOT objectDetected THEN\n  RUN intake at power 0.5\nELSE\n  STOP intake\nEND IF',explain:['The button alone is not enough: both requirements must hold.','NOT objectDetected means the sensor does not see an object.','The ELSE branch stops the intake in all other cases.'],task:'Run the lift upward at power 0.4 only when the up button is pressed AND the upper limit switch is NOT pressed. In all other cases stop the lift. Explain the case where both buttons/switches are pressed.',criteria:['Require the up button to be pressed.','Also require the upper limit switch not to be pressed.','Run the lift at 0.4 only if both requirements hold; stop otherwise.','Explain that a pressed limit switch prevents motion even with the up button pressed.'],hint:'Make a four-row truth table for button pressed/not pressed and limit pressed/not pressed.',quiz:{q:'For TRUE AND NOT TRUE, what is the result?',options:['True','False','It depends on the motor'],answer:1,why:'NOT TRUE is FALSE, and TRUE AND FALSE is FALSE.'}},
  {id:'loops',title:'Keep checking. Keep moving.',tag:'Loops & sensor updates',icon:'05',minutes:12,summary:'Repeat actions with a clear way to stop.',concept:'WHILE checks a condition before every repetition. A sensor-based loop must refresh the sensor reading, or it may keep using an old value forever. Add a time limit and an active check, then stop motors after the loop.',connection:'A robot can approach a target while repeatedly checking distance. A timeout provides an exit if the sensor never reaches the target.',example:'RESET timer\nSET distanceCm = READ distance sensor\nWHILE active AND distanceCm > 20 AND timer < 3 seconds\n  DRIVE forward at power 0.2\n  SET distanceCm = READ distance sensor\nEND WHILE\nSTOP drivetrain',explain:['If the target is already close, the loop runs zero times.','The new sensor reading affects the next condition check.','The robot stops on arrival, timeout, or end of the active period.'],task:'Approach a target until you are 10 cm or closer. Use power 0.2, re-read distance inside the loop, exit if inactive or after 4 seconds, and stop the drivetrain after the loop.',criteria:['Initialize distance and reset the timer.','Continue only while active, distance > 10 cm, and elapsed time < 4 seconds.','Drive at 0.2 and refresh distance inside the loop.','Always stop the drivetrain after the loop.'],hint:'Every condition connected by AND must stay true to keep moving. Test starting at 8 cm and a sensor stuck at 100 cm.',quiz:{q:'What happens if distance is already 8 cm when WHILE distance > 10 is checked?',options:['The loop runs once.','The loop runs forever.','The loop body is skipped.'],answer:2,why:'WHILE checks first. A false condition means zero repetitions.'}},
  {id:'functions',title:'Build reusable moves',tag:'Functions & parameters',icon:'06',minutes:12,summary:'Name a behavior and reuse it with different inputs.',concept:'A function groups instructions under a name. Parameters are named inputs that let the same function work with different values. Defining a function does not run it—you need to call it.',connection:'Teams can reuse a movement helper rather than copy the same instructions throughout an autonomous plan. Here DRIVE starts motors; WAIT lets time pass; STOP turns motors off.',example:'FUNCTION driveFor(durationSeconds, power)\n  DRIVE forward at power\n  WAIT durationSeconds\n  STOP drivetrain\nEND FUNCTION\n\nWAIT FOR START\nCALL driveFor(1, 0.3)\nCALL driveFor(2, 0.2)',explain:['The function accepts a duration and a power.','Each call substitutes its inputs into the body.','Stopping belongs inside the function so every call stops.'],task:'Define a function intakeFor(durationSeconds) that runs the intake at 0.5, waits for the supplied duration, then stops the intake. After waiting for start, call it for 1 second and then for 2 seconds.',criteria:['Define a named function with a duration parameter.','Run the intake at 0.5 and wait using the parameter.','Stop the intake inside the function.','Wait for start and call the function with 1 and 2 seconds.'],hint:'If the function always waits 1 second, is it really using the input?',quiz:{q:'What causes a function body to run?',options:['Calling the function','Naming a parameter','Writing a comment'],answer:0,why:'A definition describes the behavior; a call executes it.'}},
  {id:'debugging',title:'Become a logic detective',tag:'Tracing & testing',icon:'07',minutes:12,summary:'Find mistakes by walking through a program.',concept:'Tracing means following a program one step at a time and recording what changes. Test ordinary inputs, boundary values, and failure cases. A program can look reasonable and still do the wrong thing.',connection:'A stale sensor reading can cause a robot to keep driving. A trace helps the team find the problem before testing movement on hardware.',example:'// BUGGY: distance never changes\nSET distanceCm = READ distance sensor\nWHILE distanceCm > 10\n  DRIVE forward at power 0.2\nEND WHILE\nSTOP drivetrain',explain:['Suppose the first sensor value is 50 cm.','The condition remains based on 50 because the loop never reads again.','The intended stop may never happen. Update the reading and add exit conditions.'],task:'Repair the example: refresh the sensor in the loop, require active, add a 3-second timeout, and stop afterward. Add comments describing tests for an initial distance of 8 cm and a sensor stuck at 50 cm.',criteria:['Initialize distance and timer.','Use active, distance > 10, and a 3-second timeout in the loop condition.','Refresh distance inside the loop and stop motors after it.','Explain zero iterations at 8 cm and timeout/stop for a sensor stuck at 50 cm.'],hint:'A good test includes the input AND the behavior you expect.',quiz:{q:'Which test best checks whether a timeout works?',options:['The sensor immediately sees the target.','The sensor stays far away forever.','Change the variable name.'],answer:1,why:'A stuck far reading never satisfies the distance exit, so the timeout must stop the loop.'}},
  {id:'mission',challenge:true,title:'Your first autonomous plan',tag:'Final robot challenge',icon:'08',minutes:20,summary:'Bring it all together in one complete robot routine.',concept:'Decompose a mission into small behaviors. Use sequence for order, variables for state, conditions for choices, loops for feedback, and functions for reuse. A good plan explains both success and failure.',connection:'This is a simplified, season-independent FTC-style planning exercise, not runnable robot code. Real robot programs also need hardware setup and the appropriate SDK lifecycle.',example:'WAIT FOR START\nCALL approachTarget()\nIF targetReached AND active THEN\n  RELEASE object\nELSE\n  DISPLAY "Target not reached"\nEND IF\nSTOP all motors',explain:['Put the repeated approach behavior in a function.','Only release when the target is actually reached and the robot remains active.','Handle a timeout without pretending that the mission succeeded.'],task:'Write a complete routine that waits for start, closes the claw, and calls an approachTarget function. The function approaches at 0.2 until distance <= 10 cm, inactive, or 4 seconds elapse, refreshing the sensor and stopping afterward. Release the object only if active and within 10 cm; otherwise display a failure message. Stop all motors at the end. Add a successful test and a timeout test with expected outcomes.',criteria:['Wait for start, then close the claw and call a defined approach function.','Initialize timer/distance and use an active, distance, and timeout guarded loop with refreshed readings.','Stop after approach; make the final distance available to the release decision.','Release only when active and within 10 cm; otherwise report failure; stop all motors at the end.','Describe success and timeout tests with correct outcomes.'],hint:'Your function can return distanceCm, or you can explicitly share it. Make sure the final IF uses a current reading.',quiz:{q:'The timer expires but distance is still 40 cm. What should the robot do?',options:['Release anyway.','Keep moving forever.','Stop and report that the target was not reached.'],answer:2,why:'A timeout ends movement but does not mean the robot reached its target.'}}
];

export const tracks = [
  {id:'logic',code:'01',title:'Logic foundations',summary:'Pseudocode, variables, decisions, loops, functions, and debugging.'},
  {id:'logic-plus',code:'02',title:'Level-up logic',summary:'Toggles, timers, state machines, lists, and feedback control used in real FTC code.'},
  {id:'hardware',code:'03',title:'Hardware from code',summary:'What motors, servos, sensors, the IMU, and gamepads are, and everything code can control on them.'},
  {id:'mechanisms',code:'04',title:'Drive & mechanisms',summary:'Mecanum driving, intakes, lifts, arms, scoring, and odometry.'},
  {id:'vision',code:'05',title:'Vision & Limelight',summary:'Limelight 3A pipelines, aiming, AprilTag localization, game-piece detection, and VisionPortal.'},
];

// Each unit gets its objective, key terms, and step-by-step walkthrough from the depth files.
/** @type {Record<string, object>} */
const depth = {...logicDepth, ...logicPlusDepth, ...hardwareDepth, ...mechanismsDepth, ...visionDepth};

export const units = [
  ...foundationUnits.map(unit => ({...unit, track:'logic'})),
  ...logicPlusUnits, ...hardwareUnits, ...mechanismUnits, ...visionUnits,
].map(unit => ({...unit, ...depth[unit.id]}));
