// Objectives, key terms, and step-by-step teaching for the Vision & Limelight track.
export const visionDepth = {
  'vision-basics': {
    objective: 'Understand how a camera becomes a sensor, and what numbers vision gives your code.',
    outcomes: ['Explain what a vision pipeline does with each frame.', 'Interpret tx, ty, and ta and their signs.', 'Always check validity and freshness before acting.', 'Plan for lighting changes and missing targets.'],
    keyTerms: [
      ['Frame', 'One image from the camera.'],
      ['Pipeline', 'The processing steps that turn a frame into results.'],
      ['Target', 'The thing the pipeline is looking for: a color blob, a tag, an object.'],
      ['Crosshair', 'The reference point in the image; tx and ty are measured from it.'],
      ['Field of view (FOV)', 'How wide and tall an area the camera can see, in degrees.'],
      ['Latency', 'Delay between the moment a frame is captured and when your code gets the result.'],
      ['Exposure', 'How long the camera collects light for each frame; lower exposure reduces blur and glare.'],
    ],
    walkthrough: [
      { h: 'From pixels to numbers', p: ['A camera gives thousands of pixels per frame, far too much for robot logic. A pipeline filters the image (for a color, a shape, a tag pattern, or a trained object), finds matches, and measures them. Your code only sees the summary: valid, tx, ty, ta, IDs, and lists of detections.'] },
      { h: 'Angles from the crosshair', p: ['tx is how many degrees left (−) or right (+) the target is from the crosshair. ty is degrees below (−) or above (+). ta is the target\'s area as a percentage of the image. Bigger ta usually means closer. These three numbers are enough to aim and approach.'], code: 'tx = -8   target 8° left       -> turn left\ntx =  0   centered             -> hold\nty = +4   target above center\nta = 0.4% far away   ta = 6% close' },
      { h: 'Always check the result', p: ['Every loop: is there a result, is it valid, and is it fresh (staleness under ~100 ms)? If not, treat it as "no target." Acting on an invalid result is a common source of robots spinning or lunging for no reason.'] },
      { h: 'Lighting and motion', p: ['Event venues have different, often brighter or colored, lighting. Tune with low exposure so colors are saturated and bright spots do not wash out. Fast motion blurs frames; slow down during vision-guided moves, especially turns.'] },
      { h: 'Every vision step needs a plan B', p: ['Decide in advance what happens if vision sees nothing: use a default, search briefly, or skip. Vision should make a good autonomous better, never make it fail completely.'] },
    ],
  },
  'limelight-setup': {
    objective: 'Set up a Limelight 3A with the robot, organize pipelines, and control it from an OpMode.',
    outcomes: ['Add the Limelight to the configuration and access it in code.', 'Start the device and set a poll rate.', 'Plan and switch between numbered pipelines.', 'Monitor Limelight health on telemetry.'],
    keyTerms: [
      ['Limelight 3A', 'A smart camera that runs vision pipelines on board and sends results to the Control Hub over USB.'],
      ['Pipeline index', 'The number (0–9) of the pipeline currently running.'],
      ['Poll rate', 'How often the SDK asks the Limelight for new results, in Hz.'],
      ['Web interface', 'The browser-based tool used to build and tune pipelines.'],
      ['Snapshot', 'A saved frame used to tune pipelines offline.'],
      ['LLStatus', 'Health info from the device: temperature, FPS, current pipeline.'],
    ],
    walkthrough: [
      { h: 'What the Limelight does for you', p: ['Processing images is heavy work. The Limelight does it on its own processor, so your Control Hub loop stays fast. It returns compact results many times per second. Your job is to tune good pipelines and write code that uses the results correctly.'] },
      { h: 'Connecting and configuring', p: ['Connect the Limelight to the Control Hub, add it to the robot configuration with a name such as "limelight," and follow Limelight\'s FTC documentation for firmware and web-interface access. In code, get it from the hardware map, set the poll rate, choose a starting pipeline, and call start() during INIT.'] },
      { h: 'Plan pipeline numbers as a team', p: ['Pipelines are numbered 0–9 and stored on the device. Agree on a table, keep it in the notebook, and mirror it with constants in code. Export or back up pipeline settings, because a reset or swapped camera should not cost you a day of tuning.'], code: 'PIPE_APRILTAG = 0\nPIPE_YELLOW   = 1\nPIPE_RED      = 2\nPIPE_BLUE     = 3\nPIPE_NEURAL   = 4' },
      { h: 'Switching safely', p: ['pipelineSwitch(n) takes a moment. Compare the pipeline index reported in the result or status with the one you requested, and ignore results until they match. Otherwise you may read a frame processed by the old pipeline.'] },
      { h: 'Health checks', p: ['Show FPS, temperature, and pipeline index on telemetry during INIT. If FPS is zero or the pipeline is wrong, the drivers know before the match starts instead of after autonomous fails.'] },
    ],
  },
  'limelight-results': {
    objective: 'Read Limelight results safely and extract the specific targets your code needs from result lists.',
    outcomes: ['Check for null, validity, and staleness before using data.', 'Read the primary target\'s tx, ty, and ta.', 'Loop over fiducial, color, and detector lists.', 'Filter by class, ID, and confidence, and pick the best candidate.'],
    keyTerms: [
      ['LLResult', 'The object returned each poll with all of the Limelight\'s results.'],
      ['Primary target', 'The main target the pipeline reports in tx, ty, ta (often the largest).'],
      ['Staleness', 'How old a result is, in milliseconds.'],
      ['Fiducial result', 'An AprilTag detection with its ID and measurements.'],
      ['Detector result', 'A neural-network detection with class name and confidence.'],
      ['Confidence', 'A 0–1 score of how sure the neural network is.'],
    ],
    walkthrough: [
      { h: 'The safe-read pattern', p: ['getLatestResult() can return null (nothing yet). A non-null result can be invalid (nothing found). A valid result can be stale (the camera stopped updating). Check all three, in that order, in one helper function, and use that helper everywhere.'] },
      { h: 'Primary target vs. lists', p: ['getTx/getTy/getTa describe one primary target, which is great for simple aiming. When there may be several (three samples, two tags), use the lists: getFiducialResults, getColorResults, getDetectorResults. Each entry has its own angles and details.'] },
      { h: 'Filtering and choosing', p: ['Filter out what you do not want (wrong ID, wrong class, low confidence, tiny area), then choose the best remaining item by a score. The same "best so far" loop from the Lists unit does the job.'], code: 'detections: yellow 0.92 tx -3 | red 0.88 tx 1 | yellow 0.41 tx 0\nkeep yellow, conf > 0.6 -> [yellow 0.92 tx -3]\nbest = yellow at tx -3' },
      { h: 'Stability across frames', p: ['If the best candidate changes every frame, the robot jitters. Keep the chosen target unless it disappears for several frames or a much better one appears. Small smoothing like this makes vision-guided motion feel calm.'] },
      { h: 'Show what vision sees', p: ['Put the chosen target\'s ID or class, tx, ty, ta, and staleness on telemetry. When the robot does something odd, you can immediately see whether the problem is vision or the control code.'] },
    ],
  },
  'auto-aim': {
    objective: 'Use Limelight angles to aim and approach targets automatically, with safe gains, limits, and driver control.',
    outcomes: ['Turn toward a target with P-control on tx.', 'Estimate distance from ty and camera mounting geometry.', 'Approach to a desired distance with clamped speed.', 'Blend vision assist with driver control.'],
    keyTerms: [
      ['Auto-aim', 'Code that rotates the robot to point at a target.'],
      ['Mounting angle', 'How far up or down the camera is tilted.'],
      ['Mounting height', 'How high the camera lens is above the floor.'],
      ['Trigonometry (tan)', 'Relates angles to heights and distances in a right triangle.'],
      ['Driver assist', 'Automation that helps while the driver holds a button.'],
      ['Oscillation', 'Swinging back and forth around the target because gains are too high.'],
    ],
    walkthrough: [
      { h: 'Aim is P-control on tx', p: ['The target should be at tx = 0. So error = tx, and turn = kAim × tx. Positive tx (target right) gives a positive turn (clockwise). Clamp the turn so the robot never spins violently, and stop turning inside a small tolerance.'] },
      { h: 'Distance from ty', p: ['If the camera is at height h_cam, tilted up by angle a, and sees a target at height h_target with vertical offset ty, then distance = (h_target − h_cam) ÷ tan(a + ty). Measure the heights and angle carefully, then check the formula against a tape measure at 3–4 distances.'], code: 'h_target 20 in, h_cam 8 in, a = 15°\nty = 10° -> tan(25°) = 0.466 -> 12 / 0.466 = 25.8 in\nty = 5°  -> tan(20°) = 0.364 -> 12 / 0.364 = 33.0 in' },
      { h: 'Approach while aiming', p: ['forward = kDist × (distance − desired), clamped. Combine forward and turn in the mecanum formula so the robot drives in and aims at the same time. Slow both down as they near their goals to keep frames sharp.'] },
      { h: 'Assist, don\'t hijack', p: ['In TeleOp, let vision control only rotation (or only rotation and forward) while a button is held. The driver keeps strafe and can release the button instantly to take over. If the target disappears, return full control to the driver.'] },
      { h: 'Tuning checklist', p: ['Start with small gains. Increase until the response is quick, back off if it oscillates. Test from far left, far right, close, and far. Test with the target briefly blocked. Write the final gains and test results in the notebook.'] },
    ],
  },
  apriltags: {
    objective: 'Use AprilTags to read field information and compute the robot\'s position, including MegaTag2 with the IMU.',
    outcomes: ['Explain what AprilTags are and why their positions are known.', 'Read tag IDs for randomization or target selection.', 'Use botpose / MegaTag2 and convert units.', 'Decide when to trust a vision pose and blend it with odometry.'],
    keyTerms: [
      ['AprilTag', 'A black-and-white square code that cameras can identify and measure precisely.'],
      ['Fiducial', 'A marker placed at a known location to help measure position.'],
      ['Tag ID', 'The number encoded in the tag.'],
      ['Tag family', 'The set of patterns a tag belongs to; the camera must be set to the right family.'],
      ['botpose', 'The robot\'s field position computed from visible tags.'],
      ['MegaTag2', 'Limelight\'s localization method that uses your IMU heading for a more stable position.'],
      ['Field coordinates', 'An x/y system fixed to the field, with a defined origin and axis directions.'],
    ],
    walkthrough: [
      { h: 'Tags are landmarks', p: ['The game manual lists each tag\'s ID and location. When the camera sees a tag, it can measure exactly where the tag is relative to the camera. Since the tag\'s field position is known, the robot\'s field position can be computed in reverse. That is localization from a single image.'] },
      { h: 'IDs carry meaning', p: ['Some seasons use tag IDs to mark specific goals or to show a randomized pattern at the start of the match. Read the ID during INIT or right at the start of autonomous, store it, and plan the route around it. Always have a default if no tag is seen.'] },
      { h: 'MegaTag2 in practice', p: ['Each loop, send the IMU yaw with updateRobotOrientation, then read getBotpose_MT2. Because the heading comes from your IMU, the position estimate is steadier, especially at a distance. Poses are in meters; convert to inches (× 39.37) if your odometry uses inches.'], code: 'LOOP\n  SEND imu yaw to limelight\n  READ result\n  IF valid THEN\n    x_in = botpose_MT2.x * 39.37\n    y_in = botpose_MT2.y * 39.37' },
      { h: 'Trusting a vision pose', p: ['Vision poses can jump: glare, a partially blocked tag, or a far-away tag. Accept a pose when the robot is moving slowly, the tag is reasonably close, and the pose is near your odometry estimate. Otherwise ignore that frame.'] },
      { h: 'Coordinate systems must agree', p: ['Before combining vision and odometry, confirm both use the same origin, axis directions, units, and heading convention. Drive to a few marked spots on the field and compare both readings. Fix mismatches with a documented conversion, once.'] },
    ],
  },
  'color-detection': {
    objective: 'Find game pieces with color or neural pipelines and guide the robot to pick the best one.',
    outcomes: ['Tune a color pipeline with HSV thresholds and filters.', 'Know when a neural detector is the better choice.', 'Score and select the best candidate.', 'Turn a detection into robot motion with timeouts and fallbacks.'],
    keyTerms: [
      ['Color threshold', 'The HSV ranges a pixel must fall in to count as the target color.'],
      ['Blob', 'A connected region of matching pixels.'],
      ['Contour', 'The outline of a blob, used for shape and angle.'],
      ['Neural detector', 'A trained model that finds objects and draws boxes around them.'],
      ['False positive', 'Detecting something that is not really a target.'],
      ['Search pattern', 'Planned motion to find a target that is not visible yet.'],
    ],
    walkthrough: [
      { h: 'Color pipelines', p: ['A color pipeline keeps pixels inside hue, saturation, and value ranges, groups them into blobs, and filters by area and shape. It is fast and easy to understand, but sensitive to lighting and to other objects of the same color, like field tape or the other alliance\'s pieces.'] },
      { h: 'Neural detectors', p: ['A neural detector is trained on images of the game pieces, so it can recognize them by shape and appearance, not just color. It reports a class and confidence for each box. It is more robust in messy scenes but usually slower, and it needs a suitable trained model.'] },
      { h: 'Choosing the best piece', p: ['Score each candidate: prefer larger area or higher ty (closer, depending on mounting), smaller |tx| (more centered), and higher confidence. Ignore candidates that are too small or low-confidence. Keep the same target for several frames to avoid jitter.'], code: 'score = 2*ta - 0.1*|tx| + 1*confidence\nA: ta 3.0, tx -10, conf 0.9 -> 6.0 - 1.0 + 0.9 = 5.9\nB: ta 2.0, tx 1,   conf 0.8 -> 4.0 - 0.1 + 0.8 = 4.7\nchoose A' },
      { h: 'From detection to pickup', p: ['Center the piece (strafe or turn until |tx| is small), approach until it is close (ta or distance), then deploy the intake. Each stage needs a timeout. If a stage fails, back out to a safe state rather than wandering.'] },
      { h: 'Test on real fields', p: ['Tune with pieces on actual field tiles, near walls and tape, with the other alliance\'s pieces nearby. The pipeline that only works on a clean table will fail at the event.'] },
    ],
  },
  visionportal: {
    objective: 'Use the FTC SDK\'s VisionPortal with a webcam for AprilTags and color detection as an alternative or backup camera.',
    outcomes: ['Build a VisionPortal with an AprilTag processor.', 'Read detections and ftcPose values safely.', 'Manage CPU cost by enabling only needed processors.', 'Compare VisionPortal with a Limelight for your team\'s needs.'],
    keyTerms: [
      ['VisionPortal', 'The FTC SDK system that connects a camera to vision processors.'],
      ['Processor', 'A module that analyzes frames, like AprilTagProcessor.'],
      ['ftcPose', 'A detection\'s range, bearing, and yaw relative to the camera, in inches and degrees.'],
      ['Range', 'Straight-line distance from the camera to the tag.'],
      ['Bearing', 'Horizontal angle to the tag; positive means the tag is to the left.'],
      ['Metadata', 'Information about a known tag (like its size), needed to compute ftcPose.'],
      ['Camera calibration', 'Lens parameters needed for accurate distances.'],
    ],
    walkthrough: [
      { h: 'Built into the SDK', p: ['VisionPortal comes with the FTC SDK. Plug a supported webcam into the Control Hub, add it to the configuration, and create a portal with one or more processors. The processing runs on the Control Hub itself.'] },
      { h: 'AprilTag detections', p: ['getDetections() returns a list. For each detection with metadata, ftcPose gives range (inches), bearing (degrees, positive = left), and yaw (the tag\'s rotation). Without metadata, the SDK does not know the tag\'s size, so ftcPose is not available.'], code: 'id 20  range 34.2 in  bearing +6.5°  yaw -2.1°\n-> tag is about 34 in away, 6.5° to the LEFT' },
      { h: 'Watch the CPU', p: ['Vision on the Control Hub competes with your control loop. Use a sensible resolution, enable only the processors you need, and disable or close the portal when vision is finished. Measure loop time with and without vision running.'] },
      { h: 'Limelight or webcam?', p: ['A Limelight offloads processing, has a tuning interface, and offers MegaTag2 and neural pipelines. A webcam with VisionPortal is inexpensive and built into the SDK. Many teams use a Limelight as the main camera and keep VisionPortal knowledge as a backup or for a second view.'] },
      { h: 'Try this', p: ['Write telemetry that lists every visible tag\'s ID, range, and bearing, sorted by range. Which list pattern from the Lists unit do you need?'] },
    ],
  },
  'vision-auto': {
    objective: 'Design a vision-guided autonomous that combines odometry, AprilTags, piece detection, and safe fallbacks.',
    outcomes: ['Choose the right tool (odometry, tags, detection, IMU) for each step.', 'Structure the autonomous as a state machine with timeouts.', 'Track match time and prioritize guaranteed points.', 'Test failure modes deliberately.'],
    keyTerms: [
      ['Waypoint', 'A target pose the robot drives to.'],
      ['Pose correction', 'Updating odometry with a trusted vision measurement.'],
      ['Time budget', 'How many seconds each step is allowed to use.'],
      ['Guaranteed points', 'Scoring that does not depend on vision succeeding, like parking.'],
      ['Graceful degradation', 'Continuing with a simpler plan when something fails.'],
    ],
    walkthrough: [
      { h: 'Right tool for each job', p: ['Odometry moves between known points quickly. AprilTags correct odometry drift. Color or neural detection finds loose pieces whose location is unknown. The IMU keeps heading reliable throughout. The best routines use all four.'] },
      { h: 'Budget the 30 seconds', p: ['Estimate each state\'s time and add them up. Leave a buffer. Track elapsed time and, when too little remains for the next scoring attempt, skip straight to parking. A routine that scores less but always parks beats one that sometimes scores more and often ends in the wrong place.'], code: 'read pattern     0.0 s (INIT)\nscore preload    6.0 s\nsearch + grab    8.0 s (skip if > 18 s elapsed)\nscore second     7.0 s\npark             4.0 s\nbuffer           5.0 s' },
      { h: 'Fallbacks at every step', p: ['Search timed out? Park. Grab failed? Return and park. Tag not seen at INIT? Use the default pattern. Write the fallback next to each state in the design before writing code.'] },
      { h: 'Test the bad days', p: ['Cover the camera, remove the sample, start the robot slightly off its tile, use a tired battery. Each test should end safely and within 30 seconds. Record which fallbacks triggered and why.'] },
      { h: 'Iterate with data', p: ['After each practice run, log start pose, detected pattern, which states succeeded, time used, and final pose. Patterns in that data tell you exactly which state to improve next.'] },
    ],
  },
};
