// Objectives, key terms, and step-by-step teaching for the Logic foundations track.
export const logicDepth = {
  sequence: {
    objective: 'Write clear, ordered pseudocode that a robot (or a teammate) could follow exactly, with no guessing.',
    outcomes: ['Explain what pseudocode is and why teams plan in it before writing Java or Blocks.', 'Break a robot task into small steps that each do one thing.', 'Put steps in an order that is safe and produces the intended result.', 'Spot missing steps, such as never stopping a motor.'],
    keyTerms: [
      ['Algorithm', 'A finite, ordered list of steps that solves a problem. A recipe is an algorithm; so is an autonomous routine.'],
      ['Pseudocode', 'A plain-language description of a program\'s logic. It follows programming structure but ignores exact syntax.'],
      ['Sequence', 'Instructions that run one after another, top to bottom, in exactly the order written.'],
      ['Instruction / statement', 'One single step, such as CLOSE claw or DRIVE forward for 1 second.'],
      ['Precondition', 'Something that must already be true before a step makes sense, like "the claw is holding an object" before driving to score.'],
      ['Bug', 'Any difference between what the program does and what you meant it to do.'],
    ],
    walkthrough: [
      { h: 'Robots are perfectly literal', p: ['A human teammate fills in gaps. If you say "drive to the basket," they steer around obstacles and stop when they get there. A robot does neither. It executes exactly what the code says, in exactly the order it says it, and nothing more. If you never say STOP, the motors keep running.', 'That is why programmers plan first. Pseudocode lets the whole team read the plan, argue about it, and fix it before anyone spends time on syntax or on the field.'] },
      { h: 'How to write a good step', p: ['Each line should be one action with a clear finish. "DRIVE forward for 1 second" is good: it says what, which way, and when it ends. "Go forward a bit" is not: a robot cannot measure "a bit."', 'Use a verb first (DRIVE, TURN, OPEN, WAIT, SET, READ), then what it acts on, then any amount or unit. Consistent wording makes plans easy to scan.'], code: '// Vague                    // Clear\nGo forward a bit           DRIVE forward for 1 second\nGrab it                    CLOSE claw\nPut it down                OPEN claw' },
      { h: 'Order is logic', p: ['Swapping two lines can change everything. OPEN claw then DRIVE forward drops the object at the start. DRIVE then OPEN delivers it. When you read a sequence, ask "what is true about the robot after this line?" and carry that forward to the next line.', 'This habit is called tracing. Professional programmers do it constantly, and it is the single most useful debugging skill you will learn in this Lab.'] },
      { h: 'Worked example: deliver an object', p: ['Task: start holding an object, drive forward, and release it. First list the actions: wait for start, close claw, drive, stop, open. Then check preconditions: the claw must be closed before driving, and the robot must stop before opening so the object lands in the right spot.', 'Finally, check endings. Every motor you start must be stopped. A good question for every plan is "what is still running at the end?"'], code: 'WAIT FOR START        // nothing moves before the match starts\nCLOSE claw            // precondition for carrying\nDRIVE forward for 2 seconds\nSTOP drivetrain       // stop BEFORE releasing\nOPEN claw             // object is released at the target' },
      { h: 'Try this', p: ['Ask a teammate to act as the robot and follow your pseudocode literally, doing exactly and only what each line says. Every place they hesitate or do something silly is a place your plan is unclear. Fix those lines.'] },
    ],
  },
  variables: {
    objective: 'Use variables to store, update, and report information your robot needs to remember.',
    outcomes: ['Create a variable with a meaningful name and an initial value.', 'Update a variable using its own old value (count = count + 1).', 'Trace how a variable\'s value changes line by line.', 'Choose names and units that make code self-explaining.'],
    keyTerms: [
      ['Variable', 'A named storage spot for a value that can change while the program runs.'],
      ['Initialize', 'Give a variable its first value before using it.'],
      ['Assignment', 'Storing a value in a variable, written SET name = value. The right side is computed first, then stored on the left.'],
      ['Increment', 'Increase a variable, usually by 1: SET count = count + 1.'],
      ['Data type', 'The kind of value stored: a number, true/false (boolean), or text (string).'],
      ['Constant', 'A named value that never changes during the program, like WHEEL_DIAMETER = 4.09.'],
    ],
    walkthrough: [
      { h: 'A variable is a labeled box', p: ['Imagine a box labeled "deliveries" with a number inside. SET deliveries = 0 puts a 0 in the box. Later lines can look inside the box, or replace its contents. The label never changes; the contents can.', 'Robots use variables for counts (pieces scored), measurements (distance in cm), settings (drive power), and states (is the claw open?).'] },
      { h: 'Reading the equals sign correctly', p: ['In math, "x = x + 1" is impossible. In programming, SET x = x + 1 means: take the value currently in x, add 1, then put the result back into x. The right side is always calculated first using the OLD value.', 'Tracing helps. Write the variable\'s value after every line in a small table.'], code: 'LINE                          count\nSET count = 0                 0\nSET count = count + 1         1\nSET count = count + 1         2\nSET count = count * 3         6' },
      { h: 'Types matter', p: ['Numbers can be whole (3 pieces, 537 encoder ticks) or decimal (0.35 power, 12.4 volts). Booleans are only true or false (clawOpen, pieceDetected). Strings are text ("Ready", "Red alliance"). Mixing them up causes bugs: "5" as text is not the number 5.', 'Choosing the right type also clarifies intent. A boolean named hasPiece is easier to reason about than a number that is "1 if we have one."'] },
      { h: 'Names and units', p: ['Good names answer "what is this?" without a comment: distanceCm, liftTargetTicks, driveSpeed. Bad names make readers guess: d, x2, thing. Including the unit in the name (Cm, Ticks, Deg) prevents one of the most common robot bugs: mixing units.', 'Use CONSTANTS for numbers that are set once and never change, such as ticks per inch or servo positions. When the robot is rebuilt, you change one line instead of hunting for every 0.37 in the code.'] },
      { h: 'Try this', p: ['Trace this and fill in the final values: SET a = 4; SET b = a * 2; SET a = b - 1; SET b = a + b. (Answer: a = 7, b = 15.) If you got a different answer, find the line where your trace used a new value too early.'] },
    ],
  },
  decisions: {
    objective: 'Use IF / ELSE and comparisons to make the robot choose an action based on a sensor reading.',
    outcomes: ['Write a condition that evaluates to true or false.', 'Use the six comparison operators correctly, especially at boundaries.', 'Structure IF / ELSE so exactly one branch runs.', 'Test a decision with values below, at, and above the threshold.'],
    keyTerms: [
      ['Condition', 'A question with a true/false answer, such as distanceCm < 20.'],
      ['Boolean', 'A value that is either true or false.'],
      ['Comparison operator', 'Symbols that compare values: <, <=, >, >=, = (equal), != (not equal).'],
      ['Branch', 'One of the paths the program can take after an IF.'],
      ['Threshold', 'The cutoff value where a decision changes, like 15 cm.'],
      ['Boundary case', 'The exact threshold value, where < and <= behave differently.'],
    ],
    walkthrough: [
      { h: 'From sequence to choice', p: ['Sequences always do the same thing. Real robots need to react: stop if something is close, drive if the way is clear. IF lets a program choose. It checks a condition; if true, it runs one block; otherwise it runs the ELSE block (or skips ahead if there is no ELSE).'] },
      { h: 'Comparison operators', p: ['< less than, <= less than or equal, > greater than, >= greater than or equal, = equal, != not equal. The difference between < and <= only matters at exactly the threshold, which is exactly where robots often are.', 'Avoid = with decimal sensor readings. A distance sensor will almost never read exactly 15.000; use a range such as <= 15 instead.'], code: 'value    distance < 15    distance <= 15\n14.9     true             true\n15.0     false            true\n15.1     false            false' },
      { h: 'Reading a sensor into a variable first', p: ['Read the sensor once, store it, then decide. SET distanceCm = READ distance sensor. This gives you one consistent value for the whole decision, and you can display it on telemetry when testing.', 'If you read the sensor separately in two IFs, the readings may differ slightly and the robot may take a strange combination of actions.'] },
      { h: 'Worked example: safe approach', p: ['Goal: stop within 15 cm, otherwise creep forward. The threshold is 15, and it should stop AT 15, so use <=. Test three values: 10 (stop), 15 (stop), 30 (drive). Writing those tests down before running the robot catches most mistakes.'], code: 'SET distanceCm = READ distance sensor\nIF distanceCm <= 15 THEN\n  STOP drivetrain\nELSE\n  DRIVE forward at power 0.2\nEND IF\n// tests: 10 -> stop, 15 -> stop, 30 -> drive' },
      { h: 'Try this', p: ['Change the example so the robot backs up at power -0.2 when closer than 5 cm, stops between 5 and 15 cm, and drives otherwise. You will need to nest an IF or use ELSE IF (covered in Level-up logic). Which check must come first?'] },
    ],
  },
  boolean: {
    objective: 'Combine conditions with AND, OR, and NOT, and prove your logic with a truth table.',
    outcomes: ['Predict the result of AND, OR, and NOT for any inputs.', 'Build a truth table to check every combination.', 'Use NOT to express "is not pressed" or "has no object."', 'Use parentheses to make grouped conditions clear.'],
    keyTerms: [
      ['AND', 'True only when both conditions are true.'],
      ['OR', 'True when at least one condition is true.'],
      ['NOT', 'Flips true to false and false to true.'],
      ['Truth table', 'A table listing every combination of inputs and the resulting output.'],
      ['Interlock', 'A safety rule that blocks an action unless certain conditions are met.'],
      ['Precedence', 'The order operators are evaluated: NOT first, then AND, then OR. Parentheses override it.'],
    ],
    walkthrough: [
      { h: 'Why combine conditions?', p: ['Real decisions depend on more than one fact. Run the lift up only if the driver asks AND it is not already at the top. Score only if the lift is high AND a piece is loaded. Stop if the timer ran out OR the target was reached.'] },
      { h: 'The three operators', p: ['AND is strict: every part must be true. OR is generous: any part can be true. NOT inverts a single value. Robot safety rules usually use AND with NOT: "button pressed AND NOT limit switch pressed."'], code: 'A      B      A AND B   A OR B   NOT A\nfalse  false  false     false    true\nfalse  true   false     true     true\ntrue   false  false     true     false\ntrue   true   true      true     false' },
      { h: 'Truth tables prove your logic', p: ['With two inputs there are four combinations; with three there are eight. List them all and write what the robot should do for each. Then check that your condition produces those results. This takes two minutes and finds bugs that could take an hour on the field.'] },
      { h: 'Parentheses and precedence', p: ['NOT happens first, then AND, then OR. "a OR b AND c" means "a OR (b AND c)", which may not be what you meant. When mixing AND and OR, always add parentheses. They cost nothing and remove doubt.'], code: 'IF (upPressed OR autoRaise) AND NOT topLimit THEN\n  RUN lift up at 0.6\nELSE\n  STOP lift\nEND IF' },
      { h: 'Try this', p: ['Write the condition for an intake that runs when the driver holds the trigger OR automatic intake mode is on, but never when a piece is already detected. Then build its eight-row truth table.'] },
    ],
  },
  loops: {
    objective: 'Use WHILE loops that repeat, re-check sensors, and always have a guaranteed way to stop.',
    outcomes: ['Explain when a WHILE loop checks its condition.', 'Refresh sensor readings inside a loop.', 'Add timeout and match-active conditions so a loop always ends.', 'Stop motors after a loop exits.'],
    keyTerms: [
      ['Loop', 'A block of code that repeats.'],
      ['Iteration', 'One pass through the loop body.'],
      ['Loop condition', 'The check made before every iteration; the loop continues only while it is true.'],
      ['Infinite loop', 'A loop whose condition never becomes false. On a robot, this can mean a runaway mechanism.'],
      ['Timeout', 'A time limit that forces a loop to end even if its goal is never reached.'],
      ['Stale value', 'A variable holding an old reading that no longer matches the real world.'],
    ],
    walkthrough: [
      { h: 'Repeating with a purpose', p: ['A loop repeats until something changes. "WHILE the target is far, keep driving" lets the robot react as it moves. Each pass is an iteration. The condition is checked BEFORE every iteration, so if it is false at the start, the body never runs.'] },
      { h: 'Refresh or you are blind', p: ['A loop that uses a sensor must read it again inside the loop. Otherwise the variable keeps the first value forever and the condition never changes. This is the classic "robot drives into the wall" bug, and it happens to experienced teams too.'], code: 'SET d = READ distance      // read once before\nWHILE d > 20\n  DRIVE forward at 0.2\n  SET d = READ distance    // read again every pass\nEND WHILE' },
      { h: 'Three exits every loop needs', p: ['1) The goal: distance reached, angle reached, piece detected. 2) A timeout: something may go wrong, so give up after a reasonable time. 3) Match active: when the match or OpMode ends, stop immediately. Combine them with AND in the loop condition.', 'After the loop, stop whatever the loop started. The loop can end for three different reasons, and the motors must stop in all of them.'] },
      { h: 'Worked example: which exit happened?', p: ['After the loop ends, you may need to know why. Check the goal condition again: IF d <= 20 THEN "arrived" ELSE "timed out." Autonomous routines use this to decide whether to score or skip to a backup plan.'], code: 'RESET timer\nSET d = READ distance\nWHILE active AND d > 20 AND timer < 3 seconds\n  DRIVE forward at 0.2\n  SET d = READ distance\nEND WHILE\nSTOP drivetrain\nIF d <= 20 THEN DISPLAY "Arrived" ELSE DISPLAY "Timed out"' },
      { h: 'Try this', p: ['Trace the example three times: starting at 10 cm, starting at 50 cm and reaching 18 cm after 1 second, and with a sensor stuck at 80 cm. How many iterations and which exit for each?'] },
    ],
  },
  functions: {
    objective: 'Package a reusable robot behavior into a function with parameters, and call it with different inputs.',
    outcomes: ['Define a function with a clear name and parameters.', 'Call a function and predict what it does with given arguments.', 'Explain the difference between defining and calling.', 'Decide what belongs inside a function (like stopping motors).'],
    keyTerms: [
      ['Function', 'A named block of instructions that can be run (called) whenever needed.'],
      ['Define', 'Write the function\'s instructions once. Defining does not run it.'],
      ['Call', 'Run the function: CALL driveFor(1, 0.3).'],
      ['Parameter', 'A named input listed in the definition, like durationSeconds.'],
      ['Argument', 'The actual value passed in a call, like 1 or 0.3.'],
      ['Abstraction', 'Hiding details behind a simple name so the bigger plan is easier to read.'],
    ],
    walkthrough: [
      { h: 'Why functions exist', p: ['Autonomous routines repeat the same patterns: drive a distance, turn, raise the lift. Copying those lines everywhere means fixing a bug in ten places. A function writes the pattern once and gives it a name. Fix it once and every call is fixed.', 'Functions also make plans readable. "CALL scorePreload()" says more to a teammate than twenty lines of motor commands.'] },
      { h: 'Parameters make functions flexible', p: ['driveFor(durationSeconds, power) works for any time and speed. Inside the function, durationSeconds acts like a variable holding whatever the caller passed. The names in the definition are parameters; the values in a call are arguments.'], code: 'FUNCTION driveFor(durationSeconds, power)\n  DRIVE forward at power\n  WAIT durationSeconds\n  STOP drivetrain\nEND FUNCTION\n\nCALL driveFor(1, 0.3)   // durationSeconds = 1, power = 0.3\nCALL driveFor(2, 0.5)   // durationSeconds = 2, power = 0.5' },
      { h: 'Keep functions complete and safe', p: ['A function should leave the robot in a predictable state. If it starts a motor, it should stop it (unless its whole job is to start something). Put timeouts inside functions that wait on sensors. Then every caller gets that safety for free.'] },
      { h: 'Good function design', p: ['One job per function, named with a verb: raiseLift, openClaw, turnTo. If you need "and" to describe it, it may be two functions. Keep them short enough to read on one screen. Test each function by itself before using it in a full routine.'] },
      { h: 'Try this', p: ['Write turnFor(durationSeconds, power, direction) where direction is LEFT or RIGHT. Then write a square path: four calls to driveFor and four to turnFor. Could you shorten it with a loop that repeats 4 times?'] },
    ],
  },
  debugging: {
    objective: 'Find and fix logic errors by tracing programs step by step and designing tests that expose failures.',
    outcomes: ['Trace a program and record how variables change.', 'Design tests for normal, boundary, and failure inputs.', 'Identify common robot bugs such as stale readings and missing stops.', 'Use telemetry output to confirm what the code is really doing.'],
    keyTerms: [
      ['Trace', 'Walking through code one line at a time and recording what changes.'],
      ['Test case', 'A specific input plus the expected result.'],
      ['Expected vs. actual', 'What should happen compared with what really happened. A difference means a bug.'],
      ['Edge / boundary case', 'Inputs at the limits: exactly at the threshold, zero, maximum, empty.'],
      ['Failure case', 'A test where something goes wrong on purpose: a sensor unplugged, a target missing.'],
      ['Telemetry', 'Values the robot displays on the Driver Station while running, used to see inside the program.'],
    ],
    walkthrough: [
      { h: 'Bugs are normal', p: ['Every programmer writes bugs. Good programmers find them quickly because they have a method. Guessing and changing random numbers wastes field time. Tracing and testing find the actual cause.'] },
      { h: 'The debugging loop', p: ['1) Reproduce: make the bug happen on purpose. 2) Observe: add telemetry for the key variables. 3) Hypothesize: "I think distance never updates." 4) Test the hypothesis: watch the telemetry. 5) Fix one thing. 6) Re-test, including tests that already passed.'] },
      { h: 'A trace table in action', p: ['Tracing the buggy loop from the lesson with a starting distance of 50 shows the problem instantly: the distance column never changes, so the condition is true forever.'], code: 'iteration   distanceCm   distance > 10?   action\nstart       50           true             drive\n1           50           true             drive\n2           50           true             drive   <- never changes!' },
      { h: 'Designing strong tests', p: ['For every decision or loop, include: a normal case (starts far, arrives), a boundary case (exactly 10 cm), a zero-iteration case (already close), and a failure case (sensor stuck, target missing). Write the expected result BEFORE running. If you write it after, you tend to accept whatever happened.'] },
      { h: 'Common robot bugs checklist', p: ['Stale sensor reading in a loop. Missing STOP after a loop. < vs <= at a boundary. Wrong motor direction. Units mixed up (inches vs. cm, degrees vs. radians). A loop with no timeout. A button handled every loop instead of once per press. Keep this list handy when something goes wrong.'] },
    ],
  },
  mission: {
    objective: 'Plan a complete autonomous routine that uses every foundation skill and handles both success and failure.',
    outcomes: ['Decompose a mission into functions.', 'Combine sequence, variables, decisions, loops, and functions in one plan.', 'Design the routine so a failure (timeout) leads to a safe, honest result.', 'Write success and failure tests with expected outcomes.'],
    keyTerms: [
      ['Autonomous', 'The opening period of an FTC match when the robot runs pre-programmed code with no driver input.'],
      ['Decomposition', 'Breaking a big task into smaller sub-tasks that can each be solved alone.'],
      ['Return value', 'A result a function hands back to its caller, such as the final distance.'],
      ['Fallback', 'The planned behavior when a step does not succeed.'],
      ['Guard condition', 'A check that must be true before an action is allowed, like "within 10 cm" before releasing.'],
      ['Integration test', 'Testing the whole routine after each part has been tested separately.'],
    ],
    walkthrough: [
      { h: 'Start from the mission statement', p: ['Write one sentence: "Carry the preloaded object to the target and release it only if we actually got there." Every line of the final plan should serve that sentence. The phrase "only if we actually got there" tells you a guard condition and a fallback are needed.'] },
      { h: 'Decompose into functions', p: ['approachTarget() handles the loop, sensor refresh, timeout, and stopping. The main plan stays short: wait, close, approach, decide, stop. Short main plans are easier to reason about and easier to change between matches.'] },
      { h: 'Share information between parts', p: ['The release decision needs the final distance. Either have approachTarget RETURN it, or re-read the sensor right before deciding. Do not rely on a variable from before the loop; it is stale.'], code: 'FUNCTION approachTarget()\n  RESET timer\n  SET d = READ distance\n  WHILE active AND d > 10 AND timer < 4 seconds\n    DRIVE forward at 0.2\n    SET d = READ distance\n  END WHILE\n  STOP drivetrain\n  RETURN d\nEND FUNCTION' },
      { h: 'Plan for failure honestly', p: ['A timeout does not mean success. If the robot did not reach the target, releasing anyway wastes the object and may cause a penalty. Report the failure on telemetry so the team can fix the cause after the match.'] },
      { h: 'Test like a competition', p: ['Test the success path, the timeout path (block the robot), and the "match ends early" path (stop the OpMode mid-run). Only when all three behave safely is the routine ready for competition.'] },
    ],
  },
};
