// Vision & Limelight: cameras as sensors, from first pipeline to vision-guided autonomous.
export const visionUnits = [
  {
    id: 'vision-basics', track: 'vision', icon: 'V1', minutes: 12,
    title: 'How robot vision works', tag: 'Cameras as sensors',
    summary: 'What a camera can tell your code, and how to think about it.',
    concept: 'A camera produces images, but code needs numbers. A vision PIPELINE processes each frame and turns it into results: "a target is visible," "it is 8° to the right," "it covers 3% of the image," "the tag ID is 12." Your robot code reads those numbers exactly like any other sensor, and must handle "no target" as a normal case.',
    connection: 'FTC robots use vision to find game pieces, aim at goals, read randomization, and locate themselves on the field with AprilTags. The Limelight 3A does the processing on the camera; a webcam with the FTC VisionPortal processes on the Control Hub.',
    controls: [
      ['Pipeline', 'Which kind of detection runs', 'Color, AprilTag, neural detector, classifier, Python script'],
      ['Target valid', 'Is anything detected?', 'true / false'],
      ['tx', 'Horizontal angle from crosshair to target', 'Degrees; positive = right'],
      ['ty', 'Vertical angle from crosshair to target', 'Degrees; positive = up'],
      ['ta', 'Target size', 'Percent of image area'],
      ['Latency / staleness', 'How old the result is', 'Milliseconds'],
    ],
    deepDive: [
      { h: 'Angles, not pixels', p: 'Reporting targets as angles from the crosshair means code works the same regardless of resolution. tx = 0 means the target is dead center horizontally.' },
      { h: 'Vision is slower than other sensors', p: 'A camera delivers maybe 30–90 results per second, and each is a few tens of milliseconds old. Fast turns blur images and make results lag. Aim smoothly, and slow down near the target.' },
      { h: 'Lighting is your enemy', p: 'Event lighting differs from your practice room. Color pipelines especially need re-tuning at events. Lock exposure settings rather than using auto exposure when possible.' },
      { h: 'Always have a fallback', p: 'If vision sees nothing, autonomous should still do something sensible: a default position, a search pattern, or skipping that step.' },
    ],
    example: 'SET result = READ camera latest result\nIF result is valid THEN\n  DISPLAY "Target", result.tx, result.ty, result.ta\n  IF ABS(result.tx) < 2 THEN\n    DISPLAY "Centered"\n  END IF\nELSE\n  DISPLAY "No target"\nEND IF',
    explain: ['Always check validity before using the numbers.', 'tx near 0 means the target is centered.', '"No target" gets its own branch.'],
    pitfalls: ['Using tx without checking validity (it may be 0 from "nothing").', 'Tuning only in one lighting condition.', 'Turning so fast the camera cannot keep up.'],
    task: 'Write pseudocode that reads the latest vision result each loop and sets a driver message: "No target" if invalid; "Turn LEFT" if tx < -3; "Turn RIGHT" if tx > 3; otherwise "LOCKED". Also show "Too close" when ta > 12 regardless of direction. Explain why checking validity must come first.',
    criteria: ['Check validity before using tx or ta.', 'Use tx thresholds of ±3 correctly (negative = left).', 'Show LOCKED when -3 ≤ tx ≤ 3.', 'Add a ta > 12 "Too close" message as a separate check.', 'Explain that invalid results may still report tx = 0 and would look "locked."'],
    hint: 'What would tx be if nothing is seen? Would that look centered?',
    quiz: { q: 'tx = -8. Where is the target?', options: ['8° to the right', '8° to the left', '8° above center'], answer: 1, why: 'Negative tx means the target is left of the crosshair.' },
  },
  {
    id: 'limelight-setup', track: 'vision', icon: 'V2', minutes: 16,
    title: 'Limelight 3A setup & pipelines', tag: 'Getting the Limelight talking to code',
    summary: 'Connect, configure, and switch pipelines from your OpMode.',
    concept: 'The Limelight 3A is a smart camera: it runs the vision pipeline itself and sends finished results to the Control Hub over USB. You tune pipelines in its web interface (up to 10, numbered 0–9) and your code chooses which one runs with pipelineSwitch. Code must start the Limelight, set a poll rate, and read results every loop.',
    connection: 'One pipeline might find AprilTags for localization, another might find yellow samples, another might run a neural detector. Autonomous can switch between them as the match progresses.',
    controls: [
      ['Robot configuration', 'Device name, e.g. "limelight"', 'Add the Limelight 3A to the config'],
      ['start() / stop()', 'Begin or end polling results', 'Call start before reading'],
      ['setPollRateHz', 'How often code asks for results', 'e.g. 100'],
      ['pipelineSwitch(n)', 'Choose the active pipeline', '0 to 9'],
      ['getStatus()', 'Temperature, FPS, current pipeline', 'Useful for telemetry'],
      ['Web interface', 'Tune thresholds, exposure, tags, crosshair', 'In a browser; see Limelight FTC docs for the address'],
    ],
    deepDive: [
      { h: 'Pipeline types', p: 'Color (find blobs by hue/saturation/value), AprilTag / fiducial (find tags, IDs, and robot pose), Neural Detector (find trained objects with boxes), Neural Classifier (label the whole image), and Python SnapScripts (your own OpenCV code on the camera).' },
      { h: 'Plan your pipeline numbers', p: 'Write a team table: 0 = AprilTags, 1 = yellow sample, 2 = red sample, 3 = blue sample. Use named constants in code so pipelineSwitch(PIPE_YELLOW) reads clearly.' },
      { h: 'Switching takes a moment', p: 'After pipelineSwitch, wait until the result\'s pipeline index matches before trusting the data. Otherwise you may read one frame from the old pipeline.' },
      { h: 'Mounting in code', p: 'Record the camera height, tilt angle, and offset from the robot center. Distance estimates and pose calculations depend on these numbers being right.' },
    ],
    example: 'INIT:\n  GET limelight = hardware "limelight"\n  SET poll rate = 100 Hz\n  SWITCH pipeline to APRILTAG (0)\n  START limelight\n\nLOOP:\n  SET status = READ limelight status\n  DISPLAY "LL pipeline", status.pipeline, "FPS", status.fps, "Temp", status.temp\n  IF autonomous needs samples THEN\n    SWITCH pipeline to YELLOW (1)\n  END IF',
    explain: ['Start polling once during INIT.', 'Telemetry confirms which pipeline is active and that the camera is healthy.', 'Code switches pipelines when the task changes.'],
    java: 'Limelight3A limelight = hardwareMap.get(Limelight3A.class, "limelight");\nlimelight.setPollRateHz(100);\nlimelight.pipelineSwitch(0);\nlimelight.start();\n\nLLStatus status = limelight.getStatus();\ntelemetry.addData("LL", "pipe %d  fps %.0f  temp %.1fC",\n    status.getPipelineIndex(), status.getFps(), status.getTemp());',
    pitfalls: ['Forgetting limelight.start(), so results never update.', 'Assuming the pipeline switched instantly.', 'Tuning pipelines on one laptop and not saving/exporting them for the team.'],
    task: 'Write INIT and loop pseudocode for a Limelight with three pipelines: 0 = AprilTag, 1 = yellow samples, 2 = alliance-color samples. Start on 0. When the driver presses D-pad left, cycle to the next pipeline (0→1→2→0) with edge detection. Only trust results once result.pipelineIndex equals the requested pipeline. Show requested pipeline, active pipeline, FPS, and temperature on telemetry.',
    criteria: ['Get the device, set the poll rate, choose pipeline 0, and start in INIT.', 'Cycle pipelines 0→1→2→0 on a D-pad left edge.', 'Ignore results until the reported pipeline matches the requested one.', 'Display requested vs. active pipeline, FPS, and temperature.'],
    hint: 'Store requestedPipeline separately from what the camera reports.',
    quiz: { q: 'Where does a Limelight 3A run its vision processing?', options: ['On the Control Hub', 'On the Limelight itself', 'On the Driver Station phone'], answer: 1, why: 'The Limelight processes frames on the camera and sends results to the hub.' },
  },
  {
    id: 'limelight-results', track: 'vision', icon: 'V3', minutes: 14,
    title: 'Reading Limelight results', tag: 'LLResult: tx, ty, ta, staleness & lists',
    summary: 'Get trustworthy numbers from every frame.',
    concept: 'Each loop, getLatestResult() returns an LLResult. Check that it is not null and isValid(). Then read tx, ty, ta for the primary target, check staleness (how many ms old it is), and, for detailed work, read LISTS of results: fiducial (AprilTag) results, color results, or detector results. Each list entry has its own angles and details.',
    connection: 'Aiming, lining up with a sample, and reading tags all start with the same few lines of "is this result good?" code.',
    controls: [
      ['getLatestResult()', 'Newest result (may be null)', 'LLResult'],
      ['isValid()', 'Did the pipeline find something?', 'true / false'],
      ['getTx() / getTy() / getTa()', 'Primary target angles and area', 'Degrees, degrees, % of image'],
      ['getStaleness()', 'Age of the result', 'Milliseconds'],
      ['getFiducialResults()', 'Every AprilTag seen', 'List: ID, angles, poses'],
      ['getColorResults() / getDetectorResults()', 'Every color blob or detected object', 'List: angles, area, class name, confidence'],
    ],
    deepDive: [
      { h: 'The "good result" check', p: 'result != null AND result.isValid() AND staleness < ~100 ms. Wrap this in a function like hasFreshTarget() so every part of your code uses the same rule.' },
      { h: 'Picking from a list', p: 'The primary target is usually the largest. If you need a specific one (a certain tag ID, or the closest sample to the center), loop over the list and choose it yourself, just like the Lists unit.' },
      { h: 'Neural detector results', p: 'Each detection has a class name (for example "yellow_sample") and a confidence from 0 to 1. Ignore low-confidence detections, for example below 0.6.' },
      { h: 'Python SnapScripts', p: 'A custom Python pipeline can send back an array of numbers you define (getPythonOutput). Document what each index means for your team.' },
    ],
    example: 'FUNCTION freshResult()\n  SET r = READ limelight latest result\n  IF r = NONE OR NOT r.valid THEN RETURN NONE\n  IF r.staleness > 100 ms THEN RETURN NONE\n  RETURN r\nEND FUNCTION\n\nSET r = freshResult()\nIF r != NONE THEN\n  FOR EACH d IN r.detectorResults\n    IF d.className = "yellow" AND d.confidence > 0.6 THEN\n      DISPLAY "Yellow at", d.tx\n    END IF\n  END FOR\nEND IF',
    explain: ['One helper decides whether a result is usable.', 'Stale data is treated like no data.', 'Detections are filtered by class and confidence.'],
    java: 'LLResult r = limelight.getLatestResult();\nif (r != null && r.isValid() && r.getStaleness() < 100) {\n    double tx = r.getTx();\n    double ty = r.getTy();\n    double ta = r.getTa();\n    for (LLResultTypes.FiducialResult f : r.getFiducialResults()) {\n        telemetry.addData("Tag " + f.getFiducialId(), "tx %.1f", f.getTargetXDegrees());\n    }\n    for (LLResultTypes.DetectorResult d : r.getDetectorResults()) {\n        telemetry.addData(d.getClassName(), "conf %.2f", d.getConfidence());\n    }\n}',
    pitfalls: ['Not checking for null.', 'Acting on a stale result after the camera disconnects.', 'Assuming the primary target is the one you want.'],
    task: 'Write a function bestSample(result) that returns the detector result closest to the center (smallest |tx|) with className "yellow" or our alliance color and confidence above 0.6, or NONE. Handle a null or invalid result, stale data over 100 ms, and an empty list. Then show how the TeleOp loop uses it to display the chosen sample\'s tx.',
    criteria: ['Handle null, invalid, and stale (>100 ms) results by returning NONE.', 'Loop over detector results and filter by class (yellow or alliance) and confidence > 0.6.', 'Choose the smallest absolute tx.', 'Return NONE for an empty or fully filtered list, and use the function in the loop.'],
    hint: 'Keep best = NONE and replace it when a candidate has a smaller ABS(tx).',
    quiz: { q: 'A result is valid but its staleness is 450 ms. What should code do?', options: ['Use it; valid means good', 'Treat it as no data', 'Double the tx value'], answer: 1, why: 'Nearly half a second old is too stale. The robot or target has probably moved.' },
  },
  {
    id: 'auto-aim', track: 'vision', icon: 'V4', minutes: 16,
    title: 'Auto-aim & approach', tag: 'Using tx, ty & ta to line up',
    summary: 'Turn to face a target and drive to the right distance automatically.',
    concept: 'Aiming is P-control where the error is tx: turn = kP × tx (positive tx means target to the right, so turn right). Approaching uses distance. You can estimate distance from ty with trigonometry if the camera height and angle are known, or use ta (bigger = closer) as a simpler signal. Combine them with mecanum to aim and approach at once.',
    connection: 'Auto-aligning to a scoring target or driving up to a sample while the driver holds a button can save seconds every cycle.',
    controls: [
      ['Turn command', 'Rotate toward the target', 'rx = kAim × tx (clamped)'],
      ['Distance estimate', 'How far the target is', 'From ty and mounting geometry, or ta'],
      ['Forward command', 'Close the distance', 'y = kDist × (distance − desired)'],
      ['Strafe command (mecanum)', 'Slide sideways to center', 'Alternative to turning'],
    ],
    deepDive: [
      { h: 'Distance from ty', p: 'distance = (targetHeight − cameraHeight) ÷ tan(cameraAngle + ty). Angles must be in radians for tan. Measure heights carefully, and verify with a tape measure at several distances.' },
      { h: 'Turn or strafe?', p: 'Turning keeps the camera pointed at the target. Strafing keeps the robot\'s heading fixed, useful when the mechanism must stay square to a wall. Mecanum can do either.' },
      { h: 'Losing the target', p: 'If the target disappears for a moment, hold the last command briefly or stop. Do not keep turning at full power searching blindly.' },
      { h: 'Driver-assist', p: 'In TeleOp, a common pattern is: while the driver holds a button, vision controls rotation; the driver still controls forward and strafe. Releasing the button returns full control.' },
    ],
    example: 'SET r = freshResult()\nIF assistButton held AND r != NONE THEN\n  SET rx = clamp(0.025 * r.tx, -0.4, 0.4)\n  SET dist = (TAG_HEIGHT - CAM_HEIGHT) / TAN(CAM_ANGLE + r.ty)\n  SET y = clamp(0.03 * (dist - 18), -0.4, 0.4)\nELSE\n  SET rx = driver right stick x\n  SET y = driver forward\nEND IF\nCALL setMecanum(y, driverStrafe, rx)',
    explain: ['Positive tx gives positive rx, turning right toward the target.', 'The ty formula estimates inches to the target; the robot drives to 18 in.', 'Without a fresh target, the driver has full control.'],
    java: 'LLResult r = limelight.getLatestResult();\nif (gamepad1.left_bumper && r != null && r.isValid()) {\n    rx = Range.clip(K_AIM * r.getTx(), -0.4, 0.4);\n    double angle = Math.toRadians(CAM_ANGLE_DEG + r.getTy());\n    double dist = (TARGET_H - CAM_H) / Math.tan(angle);\n    y = Range.clip(K_DIST * (dist - 18), -0.4, 0.4);\n}',
    pitfalls: ['Wrong sign so the robot turns away and spins.', 'Degrees passed to tan.', 'Gains so high the robot oscillates around the target.'],
    task: 'Camera height 8 in, target center height 20 in, camera tilted up 15°. The Limelight reports ty = 10°. Compute the distance (tan 25° ≈ 0.466). Then write driver-assist pseudocode: while left bumper is held and a fresh target exists, vision controls rotation (kAim = 0.02, clamp ±0.35) and forward to stop at 24 in (kDist = 0.03, clamp ±0.4); the driver keeps strafe. Otherwise normal driving.',
    criteria: ['Compute distance ≈ (20 − 8) ÷ 0.466 ≈ 25.8 in.', 'Use rx = kAim × tx with clamp ±0.35 (positive tx turns right).', 'Use forward = kDist × (distance − 24) with clamp ±0.4.', 'Only assist while the bumper is held AND a fresh target exists; otherwise normal driving; driver keeps strafe.'],
    hint: '12 ÷ 0.466. Then the error is distance − 24.',
    quiz: { q: 'tx = 5 and kAim = 0.03. What rotation command is sent?', options: ['0.15 (turn right)', '-0.15 (turn left)', '5'], answer: 0, why: '0.03 × 5 = 0.15; positive tx means the target is right, so turn right.' },
  },
  {
    id: 'apriltags', track: 'vision', icon: 'V5', minutes: 18,
    title: 'AprilTags & robot localization', tag: 'Tag IDs, botpose & MegaTag2',
    summary: 'Use field tags to know exactly where the robot is.',
    concept: 'AprilTags are printed square codes with an ID. Because their positions on the field are known, seeing one lets the Limelight calculate the ROBOT\'s position on the field (botpose). MegaTag2 improves this by combining the tag with your IMU heading, which you send to the Limelight every loop. Code can use the pose directly, or use it to correct odometry drift.',
    connection: 'Tags answer "where am I?" at any point in a match. Some games also use tag IDs to signal randomization or to mark specific goals.',
    controls: [
      ['Fiducial ID', 'Which tag was seen', 'Integer'],
      ['botpose', 'Robot position from tags', 'x, y (meters, field coordinates) + orientation'],
      ['updateRobotOrientation(yaw)', 'Send IMU heading for MegaTag2', 'Degrees, every loop'],
      ['botpose_MT2', 'MegaTag2 robot pose', 'Pose3D'],
      ['Tag count / distance', 'How trustworthy the pose is', 'More tags and closer = better'],
    ],
    deepDive: [
      { h: 'Units and coordinates', p: 'Limelight poses are in meters in the field coordinate system (origin at field center). Odometry is often in inches. Convert with 1 m = 39.37 in, and make sure both systems use the same axis directions and heading convention.' },
      { h: 'MegaTag2', p: 'Plain botpose computes heading from the tag, which gets noisy at a distance. MegaTag2 trusts your IMU heading instead and solves only for position. It is usually more stable. Call updateRobotOrientation with the current yaw BEFORE reading the result each loop.' },
      { h: 'When to trust a pose', p: 'Reject poses when the robot is spinning fast, when the tag is very far away, or when the result jumps a large distance from odometry in one frame. Blend gently or reset only when the robot is nearly still.' },
      { h: 'Reading randomization', p: 'If a game uses tag IDs to signal something (like which pattern is active), read the ID during INIT or at the start of autonomous and store it before driving.' },
    ],
    example: 'LOOP:\n  SET yaw = READ imu yaw degrees\n  SEND yaw to limelight (MegaTag2)\n  SET r = freshResult()\n  IF r != NONE AND tag count >= 1 THEN\n    SET p = r.botpose_MT2\n    SET xIn = p.x * 39.37\n    SET yIn = p.y * 39.37\n    IF robot speed < 5 in/s AND distance(xIn, yIn, odometry) < 6 in THEN\n      SET odometry pose = (xIn, yIn, yaw)\n    END IF\n  END IF',
    explain: ['The IMU heading is sent before reading, as MegaTag2 requires.', 'Meters are converted to inches to match odometry.', 'Odometry is only corrected when the robot is slow and the vision pose is believable.'],
    java: 'double yaw = imu.getRobotYawPitchRollAngles().getYaw(AngleUnit.DEGREES);\nlimelight.updateRobotOrientation(yaw);\nLLResult r = limelight.getLatestResult();\nif (r != null && r.isValid()) {\n    Pose3D p = r.getBotpose_MT2();\n    double xIn = p.getPosition().x * 39.37;\n    double yIn = p.getPosition().y * 39.37;\n    for (LLResultTypes.FiducialResult f : r.getFiducialResults()) {\n        int id = f.getFiducialId();\n    }\n}',
    pitfalls: ['Mixing meters and inches.', 'Forgetting updateRobotOrientation for MegaTag2.', 'Snapping odometry to every noisy vision pose, making the robot jerk.'],
    task: 'Write pseudocode that, during autonomous INIT, reads the tag ID visible on the field and stores which of three patterns (tag 21, 22, or 23) is active, with a default if none is seen. Then, during autonomous, correct odometry from MegaTag2 only when the robot is moving slower than 5 in/s and the vision pose is within 8 inches of odometry. Explain why the 8-inch rule protects you.',
    criteria: ['Read tag IDs during INIT and store pattern 21/22/23, with a default when none is seen.', 'Send IMU yaw to the Limelight before reading MegaTag2 each loop.', 'Convert meters to inches.', 'Only correct odometry when slow (< 5 in/s) and within 8 in.', 'Explain that the 8-inch rule rejects bad or misidentified tag readings.'],
    hint: 'What if the camera briefly sees a tag reflected, or computes a wild pose from far away?',
    quiz: { q: 'What extra input does MegaTag2 need from your code each loop?', options: ['Battery voltage', 'The robot\'s IMU heading', 'The gamepad state'], answer: 1, why: 'MegaTag2 uses your heading to compute a more stable position.' },
  },
  {
    id: 'color-detection', track: 'vision', icon: 'V6', minutes: 14,
    title: 'Finding game pieces', tag: 'Color pipelines & neural detectors',
    summary: 'Detect samples on the field and pick the best one to grab.',
    concept: 'Color pipelines find regions ("blobs") within a hue, saturation, and value range. Neural detectors are trained to recognize objects and report a class and confidence. Either gives you a list of candidates with tx, ty, and area. Code picks the best candidate and lines up the intake, sometimes turning a claw or wrist to match the piece\'s angle.',
    connection: 'Grabbing pieces from the field automatically in autonomous, or helping the driver line up in TeleOp, can double a team\'s cycle count.',
    controls: [
      ['HSV thresholds (web UI)', 'Which colors count', 'Hue, saturation, value ranges'],
      ['Area filters', 'Ignore blobs that are too small or too large', '% of image'],
      ['Blob list', 'Every matching region', 'tx, ty, ta, and corners'],
      ['Detector class / confidence', 'What object and how sure', 'Name, 0–1'],
      ['Wrist/claw servo', 'Match the piece\'s rotation', 'Servo position from angle'],
    ],
    deepDive: [
      { h: 'Tuning a color pipeline', p: 'Set exposure low so colors are saturated and bright lights do not wash out. Narrow the hue range until only the piece lights up. Then raise the minimum area to drop tiny false blobs.' },
      { h: 'Choosing the best piece', p: 'Score candidates: closest (largest ty or ta, depending on mounting), most centered (smallest |tx|), and not blocked. Pick the highest score, and stick with it for a few frames rather than switching every frame.' },
      { h: 'Converting to intake position', p: 'With a known camera mount, tx and ty map to a field location relative to the robot. Measure a few points, then fit a simple formula or lookup table for "how far to extend" and "how much to strafe."' },
      { h: 'Built-in FTC option', p: 'The FTC SDK also includes a color blob locator processor for webcams through VisionPortal, with similar ideas: color range, blob list, area and shape filters.' },
    ],
    example: 'SET r = freshResult()\nSET best = NONE\nFOR EACH blob IN r.colorResults\n  IF blob.ta > 0.5 THEN\n    SET score = blob.ta * 2 - ABS(blob.tx) * 0.1\n    IF best = NONE OR score > bestScore THEN\n      SET best = blob\n      SET bestScore = score\n    END IF\n  END IF\nEND FOR\nIF best != NONE THEN\n  SET strafe = clamp(0.03 * best.tx, -0.3, 0.3)\nEND IF',
    explain: ['Tiny blobs are ignored.', 'Bigger (closer) and more centered blobs score higher.', 'The robot strafes to center the chosen piece.'],
    java: 'for (LLResultTypes.ColorResult c : r.getColorResults()) {\n    double tx = c.getTargetXDegrees();\n    double ty = c.getTargetYDegrees();\n    double area = c.getTargetArea();\n    // score and choose the best candidate\n}',
    pitfalls: ['Hue ranges so wide that field tiles or the other alliance\'s pieces match.', 'Switching targets every frame, causing jittery motion.', 'Not re-tuning under event lighting.'],
    task: 'Write autonomous pseudocode that searches for a yellow sample: if none is visible, rotate slowly (0.15) for up to 2 seconds. When one is found, choose the best candidate (larger area, more centered), strafe to center it (|tx| < 2°), then drive forward until ta > 6 or 1.5 s pass, and deploy the intake. If no sample is found in time, skip to parking.',
    criteria: ['Search by rotating slowly with a 2-second limit.', 'Select the best candidate using area and centering.', 'Center with strafe until |tx| < 2°.', 'Approach until ta > 6 or a 1.5 s timeout, then deploy the intake.', 'Fall back to parking when no sample is found.'],
    hint: 'Break it into states: SEARCH, CENTER, APPROACH, GRAB, PARK.',
    quiz: { q: 'Why ignore blobs with very small area?', options: ['They are always the wrong color', 'They are often noise or far-away reflections', 'The Limelight cannot report them'], answer: 1, why: 'Tiny detections are usually noise, glare, or objects too far away to matter.' },
  },
  {
    id: 'visionportal', track: 'vision', icon: 'V7', minutes: 14,
    title: 'Webcams & the FTC VisionPortal', tag: 'The built-in alternative',
    summary: 'Use a regular USB webcam with the FTC SDK\'s AprilTag and color processors.',
    concept: 'The FTC SDK includes VisionPortal, which runs vision on the Control Hub using a USB webcam. You add PROCESSORS, like the AprilTag processor, and read their results. AprilTag detections include a ready-made ftcPose: range (distance), bearing (angle to turn), and yaw (tag rotation), in inches and degrees. It uses more hub processing than a Limelight, but needs no extra hardware beyond a webcam.',
    connection: 'Many teams use VisionPortal as a backup camera, for a second viewpoint, or if they do not have a Limelight. The concepts are identical: validity, angles, lists, and fallbacks.',
    controls: [
      ['VisionPortal', 'Camera + processors', 'Build once in INIT'],
      ['AprilTagProcessor', 'Detect tags', 'getDetections() list'],
      ['ftcPose.range / bearing / yaw', 'Distance, angle to target, tag rotation', 'Inches, degrees, degrees'],
      ['Processor enable/disable', 'Save CPU when not needed', 'setProcessorEnabled'],
      ['Camera stream', 'Live preview on Driver Station', 'For tuning'],
    ],
    deepDive: [
      { h: 'Metadata check', p: 'A detection\'s metadata is null if the tag is not in the loaded tag library, and then ftcPose is not available. Always check metadata != null before using ftcPose.' },
      { h: 'Save the hub\'s CPU', p: 'Vision on the Control Hub competes with your control loop. Disable processors you are not using, lower resolution, and consider stopping the stream when done.' },
      { h: 'Camera calibration', p: 'Accurate range and pose need lens calibration for your webcam model and resolution. Common webcams have built-in calibrations; others need one supplied.' },
    ],
    example: 'INIT:\n  CREATE aprilTag processor\n  CREATE vision portal with webcam "Webcam 1" and aprilTag\nLOOP:\n  FOR EACH d IN aprilTag detections\n    IF d.metadata != NONE AND d.id = 20 THEN\n      DISPLAY "Range", d.ftcPose.range, "Bearing", d.ftcPose.bearing\n    END IF\n  END FOR',
    explain: ['The portal and processor are built once.', 'Every detection is checked for metadata before using ftcPose.', 'Range and bearing are ready for driving code.'],
    java: 'AprilTagProcessor tags = AprilTagProcessor.easyCreateWithDefaults();\nVisionPortal portal = VisionPortal.easyCreateWithDefaults(\n    hardwareMap.get(WebcamName.class, "Webcam 1"), tags);\n\nfor (AprilTagDetection d : tags.getDetections()) {\n    if (d.metadata != null && d.id == 20) {\n        telemetry.addData("Range", "%.1f in", d.ftcPose.range);\n        telemetry.addData("Bearing", "%.1f deg", d.ftcPose.bearing);\n    }\n}',
    pitfalls: ['Using ftcPose when metadata is null.', 'Running several processors at high resolution and slowing the control loop.', 'Forgetting the webcam name must match the configuration.'],
    task: 'Using VisionPortal AprilTag detections, write driver-assist pseudocode that drives toward tag 20 and stops 12 inches away, facing it. Use range for forward (P-control, clamp ±0.4) and bearing for turning (P-control, clamp ±0.3). Handle metadata == null and "tag not seen." Explain the sign you chose for turning based on bearing.',
    criteria: ['Loop through detections and select tag 20 with metadata present.', 'Forward = kP × (range − 12), clamped ±0.4.', 'Turn from bearing, clamped ±0.3, with a sign explanation.', 'Stop or return control to the driver when the tag is not seen.'],
    hint: 'In the FTC SDK, positive bearing means the tag is to the LEFT. Which rx sign turns left?',
    quiz: { q: 'What must be true before using a detection\'s ftcPose?', options: ['The tag ID is even', 'Its metadata is not null', 'The robot is stopped'], answer: 1, why: 'Without metadata (a known tag size), the SDK cannot compute ftcPose.' },
  },
  {
    id: 'vision-auto', track: 'vision', icon: 'V8', minutes: 25, challenge: true,
    title: 'Vision-guided autonomous', tag: 'Vision capstone',
    summary: 'Combine odometry, AprilTags, and piece detection in one reliable routine.',
    concept: 'A strong autonomous uses each tool for what it does best: odometry for moving between known points, AprilTags to correct position, color or neural detection to find loose pieces, and IMU heading throughout. Every vision step has a timeout and a fallback, so a missed detection never ruins the whole routine.',
    connection: 'This is the plan structure competitive teams use. The fallbacks are what make it score in every match, not just the good ones.',
    deepDive: [
      { h: 'Plan with fallbacks', p: 'For each vision step, write: what we do if it works, how long we wait, and what we do if it does not. "Skip and park" is a valid fallback.' },
      { h: 'Test the failures', p: 'Cover the camera during practice runs. The routine should still finish safely and on time.' },
    ],
    example: 'STATE READ_PATTERN (INIT): store tag pattern or default\nSTATE DRIVE_TO_SCORE:  goTo(scorePose); correct with tags when slow\nSTATE SCORE_PRELOAD:   lift, release, lower\nSTATE SEARCH_SAMPLE:   color pipeline, 2 s timeout -> PARK if none\nSTATE GRAB_SAMPLE:     center, approach, intake, 2 s timeout\nSTATE RETURN_SCORE:    goTo(scorePose); score\nSTATE PARK:            goTo(parkPose)',
    explain: ['Each state is one clear goal.', 'Vision steps have timeouts and fallbacks.', 'Parking is always reachable.'],
    task: 'Write a complete autonomous state machine for our mecanum robot with a Limelight: read a randomization tag during INIT (default if unseen); drive to a scoring pose with odometry and MegaTag2 correction; score a preloaded piece; switch to the yellow pipeline and search for a sample (2 s timeout); grab it with centering and approach (2 s timeout); return and score; then park. Track total elapsed time and skip straight to PARK if fewer than 5 seconds remain. Include telemetry for state and time.',
    criteria: ['Read and store the randomization tag in INIT with a default.', 'Use odometry moves with MegaTag2 correction under safe conditions.', 'Switch pipelines and search/grab with timeouts and fallbacks.', 'Score the preload and the collected piece with the lift/release sequence.', 'Check remaining match time and jump to PARK if under 5 s; show state and time.'],
    hint: 'Autonomous is 30 seconds. Where in the loop do you check the clock?',
    quiz: { q: 'What should happen if the sample search times out?', options: ['Keep searching until found', 'Follow the planned fallback, such as parking', 'Restart autonomous'], answer: 1, why: 'A fallback keeps the routine safe and guarantees the parking points.' },
  },
];
