import test from 'node:test';
import assert from 'node:assert/strict';
import { createApp } from './server.mjs';
async function withServer(options,run){const server=createApp(options);await new Promise(r=>server.listen(0,'127.0.0.1',r));try{await run(`http://127.0.0.1:${server.address().port}`);}finally{await new Promise(r=>server.close(r));}}
const request=(base,body,headers={})=>fetch(base+'/api/feedback',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:typeof body==='string'?body:JSON.stringify(body)});
const answer={unitId:'sequence',answer:'WAIT FOR START\nCLOSE claw\nDRIVE forward for 2 seconds\nSTOP drivetrain\nOPEN claw'};
test('offline mode is explicit and cannot award completion',()=>withServer({apiKey:''},async base=>{assert.deepEqual(await (await fetch(base+'/api/status')).json(),{ai:false});const res=await request(base,answer);assert.equal(res.status,200);const data=await res.json();assert.equal(data.mode,'self-review');assert.equal(data.passed,false);assert.equal(data.improvements.length,4);}));
test('rejects malformed, missing, too short and oversized answers',()=>withServer({apiKey:''},async base=>{for(const body of ['{',{}, {...answer,answer:'x'},{...answer,unitId:'missing'},{...answer,answer:'x'.repeat(6001)}]) assert.equal((await request(base,body)).status,400);assert.equal((await request(base,{...answer,answer:'x'.repeat(17000)})).status,413);}));
test('serves app but not private files; rejects cross-origin submission',()=>withServer({apiKey:''},async base=>{for(const path of ['/','/app.js','/styles.css','/curriculum.js']) assert.equal((await fetch(base+path)).status,200);for(const path of ['/.env','/server.mjs','/package.json']) assert.equal((await fetch(base+path)).status,404);assert.equal((await request(base,answer,{Origin:'https://unrelated.example'})).status,403);}));
test('AI request uses server curriculum and parses structured feedback',()=>{const feedback={passed:true,summary:'Correct sequence.',strengths:['Stops before releasing.'],improvements:[],nextStep:'What if the claw opened earlier?'};return withServer({apiKey:'test-key',fetchImpl:async(url,init)=>{assert.equal(url,'https://api.openai.com/v1/responses');const body=JSON.parse(init.body);assert.equal(body.store,false);assert.equal(body.text.format.type,'json_schema');assert.equal(JSON.parse(body.input).criteria.length,4);return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(feedback)}]}]});}},async base=>{const response=await request(base,answer);assert.equal(response.status,200);assert.deepEqual(await response.json(),{mode:'ai',...feedback});});});
test('provider failure or refusal never awards completion',async()=>{for(const providerResponse of [new Response('',{status:401}),Response.json({status:'completed',output:[{content:[{type:'refusal',refusal:'No'}]}]}),Response.json({status:'incomplete',output:[]})]) await withServer({apiKey:'test',fetchImpl:async()=>providerResponse},async base=>{const response=await request(base,answer);assert.equal(response.status,502);assert.equal((await response.json()).passed,undefined);});});
test('rate limits AI requests',()=>withServer({apiKey:'test',fetchImpl:async()=>new Response('',{status:503})},async base=>{for(let i=0;i<10;i++)assert.equal((await request(base,answer)).status,502);assert.equal((await request(base,answer)).status,429);}));
